[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
resolution = true
skip-lint = false

[programs.devnet]
hybrid_dex = "G12WABos41DU4ic2RLea5qwCfSyvB83XdKz9CMdiJLUW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "../deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 100000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true
