[toolchain]
anchor_version = "0.30.1"
solana_version = "2.0.22"

[features]
resolution = true
skip-lint = false

[programs.devnet]
hybrid_dex = "6z1NX1CodyGPbJ8sAVirasDsYgw1xSnkyjyprSnMfvRy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../deploy.json"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 100000 tests/**/*.ts"
